package pl.wikihangman.views.swing;

import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pl.wikihangman.models.User;
import pl.wikihangman.services.AccountsService;
import pl.wikihangman.views.logging.ErrorsEnum;
import pl.wikihangman.views.swing.helpers.OptionPaneHelpers;

/**
 *
 * @author Łukasz Szafirski
 * @version 1.0.0.0
 */
public class ScoreBoardPanel extends javax.swing.JPanel {

    AccountsService accountService = null;
    
    /**
     * Creates new form ScoreBoardPanel
     */
    public ScoreBoardPanel() {
        initComponents();
    }
    
    /**
     * 
     * @param accountsService accounts service used to get user's list
     * @return this object
     */
    public ScoreBoardPanel setAccountService(AccountsService accountsService) {
        this.accountService = accountsService;
        return this;
    }
    
    /**
     * Displays active's user score above score board.
     * 
     * @param user currently logged user
     * @return this object
     */
    public ScoreBoardPanel showWithActiveUser(User user) {
        userScoreLabel.setText(String.format("%1$s: %2$d", user.getName(), user.getPoints()));
        return this;
    }
    
    /**
     * Reads player's list from database and displays theirs score in the table.
     * @return this object
     */
    public ScoreBoardPanel displayScoreBoard() {
        List<User> users = null;
        try {
            users = accountService.getPlayersList();
        } catch (IOException ioException) {
            OptionPaneHelpers.showErrorMessage(this, ErrorsEnum.DB_IO);
            return this;
        } catch (NumberFormatException numberFormatException) {
            OptionPaneHelpers.showErrorMessage(this, ErrorsEnum.DB_FORMAT);
            return this;
        }
        
        DefaultTableModel tableModel = (DefaultTableModel)scoreBoardTable.getModel();
        users.forEach(u -> tableModel.addRow(new Object[]{u.getName(), u.getPoints()})); 
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        scoreBoardTable = new javax.swing.JTable();
        userScoreLabel = new javax.swing.JLabel();

        scoreBoardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scoreBoardTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(scoreBoardTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(userScoreLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(userScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable scoreBoardTable;
    private javax.swing.JLabel userScoreLabel;
    // End of variables declaration//GEN-END:variables
}
